
SELECT * FROM customer_shoping_behaviour;

--1.what is the total revenue generated by male vs female customers

SELECT gender, SUM(purchase_amount) AS revenue
FROM customer_shoping_behaviour
GROUP BY gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

SELECT customer_id, purchase_amount
FROM customer_shoping_behaviour
WHERE discount_applied = 'Yes'
AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_shoping_behaviour);

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) AS avg_review_rating
FROM customer_shoping_behaviour
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT shipping_type, ROUND(AVG(purchase_amount),2)
FROM customer_shoping_behaviour
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

SELECT subscription_status,
COUNT(customer_id) AS total_customer,
ROUND(AVG(purchase_amount),2) AS spend_amount,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer_shoping_behaviour
GROUP BY subscription_status
ORDER BY 3,4 DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer_shoping_behaviour
GROUP BY item_purchased
ORDER BY 2 DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

WITH customer_type AS(
SELECT customer_id,previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 1 AND 10 THEN 'Returning'
	ELSE 'Loyal' 
	END AS customer_segment
FROM customer_shoping_behaviour
)
SELECT customer_segment,COUNT(*) AS No_of_customers
FROM customer_type
GROUP BY customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS(
SELECT item_purchased, category,
COUNT(customer_id) AS total_customer,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer_shoping_behaviour
GROUP BY 1,2
)
SELECT item_rank,item_purchased,category,total_customer
FROM item_counts
WHERE item_rank <=3;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
	COUNT(customer_id) AS repeat_buyers
FROM customer_shoping_behaviour
WHERE previous_purchases > 5
GROUP BY 1;


--Q10. What is the revenue contribution of each age group? 

SELECT age_group,
	SUM(purchase_amount) AS total_revenue
FROM customer_shoping_behaviour
GROUP BY 1
ORDER BY 2 DESC;















